config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'hello_world#index', as: 'root'

    resources :response, controller: :response
    post '/response/:user_id', to: 'response#create', as: 'client_response'
    get '/response/:user_id/new', to: 'response#new', as: 'new_client_response'

    resources :message, controller: :message
    post '/message/:agent_id', to: 'message#create', as: 'agent_message'

    get '/agent_login', to: 'agent_session#new'
    post '/agent_login', to: 'agent_session#create'
    delete '/agent_logout', to: 'agent_session#destroy'
    get '/agent_register', to:'agent_register#new'
    post '/agent_register', to:'agent_register#create'
      resources :agent_profile, controller: :agent_profile

    get '/user_login', to: 'user_session#new'
    post '/user_login', to: 'user_session#create'
    delete '/user_logout', to: 'user_session#destroy'
    get '/user_register', to:'user_register#new'
    post '/user_register', to:'user_register#create'
      resources :user_profile, controller: :user_profile
      resources :agent, controller: :agent


end

app/models/response.rb
class Response < ApplicationRecord
  belongs_to :user
  belongs_to :agent
end

app/controllers/response_controller.rb
class ResponseController < ApplicationController

  def new
    @agent = Agent.find(session[:agent_id])
    @client = User.find(params[:user_id])
    @newResponse = Response.new
  end

  def create
    @newResponse = Response.new(response_params)
    @newResponse.agent_id = session[:agent_id]
    @newResponse.user_id = params[:user_id]
    current_user = session[:agent_id]

    respond_to do |format|
      if @newResponse.save
        @newResponse.accept = 'true'
        format.html {redirect_to agent_profile_path(current_user), notice: 'Responded to Client' }
      else
        format.html {redirect_to action: "new", notice: "error"}
        format.json {render json: @newResponse.erros, status: :unprocessable_entity}
      end
    end
  end

  def update
    @acceptagent = Response.find(params[:id])
    if @acceptagent.update_attributes(:accept => 'True')
      @acceptagent.save
      redirect_to user_profile_path(:id => 1)
    else
      redirect_to user_profile_path(params[:id])
    end
  end

  def destroy
    @response = Response.find(params[:id])
    @response.destroy
    redirect_to user_profile_path(:id => 1), :notice => "Message deleted"
  end

  private

  def response_params
    params.require(:response).permit(:accept, :content, :user_id, :agent_id)
  end

end

app/views/response/new.html.erb
<nav class="navbar sticky-top navbar-light bg-light">
  <a class="navbar-brand" href="">Real World</a>
  <ul class="nav nav-pills" role="tablist">
     <!-- link_to "Profile", agent_profile_path  -->
    <%= link_to "Logout", agent_logout_path, :method => :delete %>
  </ul>
</nav>

<div class="container agentprofileinfo">
  <div class="row">
    <div class="col-md-12">
      <div class="respondToClient">
        <center>
            <h3>Message to Client</h3>
            <div class="messageToClient">
              <%= simple_form_for @newResponse, :url => client_response_path(@client.id) do |f| %>
                <%= f.text_area :content %><br>
              <%= f.submit %>
            <% end %>
          </div>
            <%= link_to "Back", agent_profile_path(@agent) %>
        </center>
      </div>
    </div>
  </div>
</div>