config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'hello_world#index', as: 'root'

    resources :response, controller: :response
    post '/response/:user_id', to: 'response#create', as: 'client_response'
    get '/response/:user_id/new', to: 'response#new', as: 'new_client_response'

    resources :message, controller: :message
    post '/message/:agent_id', to: 'message#create', as: 'agent_message'

    get '/agent_login', to: 'agent_session#new'
    post '/agent_login', to: 'agent_session#create'
    delete '/agent_logout', to: 'agent_session#destroy'
    get '/agent_register', to:'agent_register#new'
    post '/agent_register', to:'agent_register#create'
      resources :agent_profile, controller: :agent_profile

    get '/user_login', to: 'user_session#new'
    post '/user_login', to: 'user_session#create'
    delete '/user_logout', to: 'user_session#destroy'
    get '/user_register', to:'user_register#new'
    post '/user_register', to:'user_register#create'
      resources :user_profile, controller: :user_profile
      resources :agent, controller: :agent


end

app/models/agent.rb
class Agent < ApplicationRecord
  has_many :messages
  has_many :reviews
  has_many :responses
  has_many :messaged_users, through: :messages, source: :user
  has_many :reviewed_users, through: :reviews, source: :user
  has_many :responsed_user, through: :responses, source: :user

  has_secure_password validations: false
  # attr_accessor :password
  # EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  # validates :name, :presence => true, :length => { :in => 3..20 }
  # validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
  # validates :password, :presence => true
  # validates_length_of :password, :in => 6..20, :on => :create
  #
  # before_save :encrypt_password
  # after_save :clear_password
  #
  # def encrypt_password
  #   if password.present?
  #     self.salt = BCrypt::Engine.generate_salt
  #     self.password= BCrypt::Engine.hash_secret(password, salt)
  #   end
  # end
  # def clear_password
  #   self.password = nil
  # end

  def agent_params
     params.require(:agent).permit(:name, :email, :password, :bio, :specialty, :location)
  end

end

app/controllers/agent_controller.rb
class AgentController < ApplicationController
  layout "agent"

  def index #display all agents for users
    @agents = Agent.all
    @agent_props = Agent.name
    @agentmessage = Message.where(user_id: params[:id])
  end

  def show #display ONE agent for users
    @agent = Agent.find(params[:id])
    @agentmessage = Message.where(user_id: params[:id])
    # @agentname = Agent.find(params[:id]).name
    # @agentbio = Agent.find(params[:id]).bio
    # @agentspecialty = Agent.find(params[:id]).specialty
    # @agentlocation = Agent.find(params[:id]).location
    @agentreview = Review.where(agent_id: params[:id])
    @newMessage = Message.new

    @resp = Response.where(agent: @agent).first
  end

  def new
  end

  def edit #edit page for agent settings
    @agent = Agent.find(params[:id])
  end

  def create #process request information from users
    @agent = Agent.find(params[:id])
    @request = Message.new(params[agentrequest_params])
    if @request.save
      redirect_to action: :index
    else
      render 'show'
    end
  end

  def edit #edit page for agent settings
    @agent = Agent.find(params[:id])
  end

  def update #process edited information
    @agent = Agent.find(params[:id])
    if @agent.update_attributes(agent_params)
      redirect_to agent_profile_path(@agent)
      flash[:success] = "Your profile has been updated"
    else
      redirect_to edit_agent_profile_path, notice: "error"
    end
  end

  private
    def agentrequest_params
      params.require(:message).permit(:content)
    end

    def agent_params
      params.require(:agent).permit(:email, :password,:bio, :specialty, :location)
    end

end

app/views/agent/index.html.erb
<nav class="navbar sticky-top navbar-light bg-light">
  <%= link_to "Real World", agent_index_path %>
  <ul class="nav nav-pills" role="tablist">
    <li role="presentation"><a class="bannerbtn" href="http://localhost:3000/user_profile/1">Profile</a></li>
    <%= link_to "Logout", user_logout_path, :method => :delete %>
  </ul>
</nav>


<div class="sorting">
  <div class="btn-group btn-group-justified active" role="group" aria-label="...">
    <div class="btn-group" role="group">
      <button type="button" class="btn btn-default">Most Reviewed</button>
    </div>
    <div class="btn-group" role="group">
      <button type="button" class="btn btn-default">Top Rated</button>
    </div>
    <div class="btn-group" role="group">
      <button type="button" class="btn btn-default">Specialty</button>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-12 agentprofileinfo">
        <center><h4>A G E N T S</h4></center>
        <div class="scrollbar scrollbar-morpheus-den">
          <div class="force-overflow">
            <p>
              <%= react_component("Agentlist", props: @agent_props, prerender: false) %>
              <% @agents.each do |agent| %>
                <ul>
                  <p class="listname">
                    <h4><%= agent.name %> </h4>
                    Specialty: <%= agent.specialty %>
                    <span class="requestlink">
                      <%= link_to "Request", agent %>
                    </span>
                  </p>
                </ul>
              <% end %>
            </p>
          </div>
        </div>
    </div>
  </div>
</div>

app/views/agent/show.html.erb
<nav class="navbar sticky-top navbar-light bg-light">
  <%= link_to "Real World", agent_index_path %>
  <ul class="nav nav-pills" role="tablist">
    <li role="presentation"><a class="bannerbtn" href="http://localhost:3000/user_profile/1">Profile</a></li>
    <%= link_to "Logout", user_logout_path, :method => :delete %>
  </ul>
</nav>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="agentprofileinfo">
        <img class="bigdisplay" src="<%= @agent.img %>" alt="Profile Picture"></img>
        <p>
          <span class="agentname"><%= @agent.name %></span>
        </p>
        <div class="scrollbar scrollbar-morpheus-den agentinfo">
          <div class="force-overflow">
            <p>
              <b>Specialized Location:</b> <%= @agent.location %><br>
              <b>Specialty:</b> <%= @agent.specialty %><br>
            </p>
            <p><b>Biography:</b><br>
              <%= @agent.bio %>
            </p>
          </div>
        </div>
        <div class="request">
          <h5 class="requesttitle">Request Agent</h5>
          <%= simple_form_for @newMessage, :url => agent_message_path(@agent.id)  do |f| %>
            <p class="agentrequesttext">
              <%= f.text_area :content %><br>
            </p>
            <%= f.submit %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>