config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'hello_world#index', as: 'root'

    resources :response, controller: :response
    post '/response/:user_id', to: 'response#create', as: 'client_response'
    get '/response/:user_id/new', to: 'response#new', as: 'new_client_response'

    resources :message, controller: :message
    post '/message/:agent_id', to: 'message#create', as: 'agent_message'

    get '/agent_login', to: 'agent_session#new'
    post '/agent_login', to: 'agent_session#create'
    delete '/agent_logout', to: 'agent_session#destroy'
    get '/agent_register', to:'agent_register#new'
    post '/agent_register', to:'agent_register#create'
      resources :agent_profile, controller: :agent_profile

    get '/user_login', to: 'user_session#new'
    post '/user_login', to: 'user_session#create'
    delete '/user_logout', to: 'user_session#destroy'
    get '/user_register', to:'user_register#new'
    post '/user_register', to:'user_register#create'
      resources :user_profile, controller: :user_profile
      resources :agent, controller: :agent


end

app/controllers/agent_profile_controller.rb
class AgentProfileController < ApplicationController
  layout 'agent_profile'
  def index
    @users = User.all
  end

  def show #agentprofile
    @agent = Agent.find(params[:id])
    @clientmessage = Message.where(agent_id: params[:id])
    @clientreview = Review.where(agent_id: params[:id])

    def average(rating)
      calculate(:average, rating)
    end

  end

  def edit #edit page for agent settings
    @agent = Agent.find(params[:id])
  end

  def update #process edited information
    @agent = Agent.find(params[:id])
    if @agent.update_attributes(agent_params)
      @agent.save
      redirect_to agent_profile_path(@agent)
      flash[:success] = "Your profile has been updated"
    else
      redirect_to edit_agent_profile_path, notice: "error"
    end
  end

  private
    def agent_params
      params.require(:agent).permit(:name, :email, :password, :bio, :specialty, :location, :img)
    end

end

app/views/agent_profile/edit.html.erb
<nav class="navbar sticky-top navbar-light bg-light">
  <a class="navbar-brand" href="http://localhost:3000/agent">Real World</a>
  <ul class="nav nav-pills" role="tablist">
    <%= link_to "Profile", agent_profile_path %>
    <%= link_to "Logout", agent_logout_path, :method => :delete %>
  </ul>
</nav>


<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="profileinfoedit">
        <center>
          <p>
              <h4> Edit Profile </h4>
              <h3><%= @agent.name %></h3>
              <%= simple_form_for @agent do |f| %>

              <div class="scrollbar scrollbar-morpheus-den editpage">
                <p>
                  <%= f.label :email %><br />
                  <%= f.text_field :email, class: 'form-control'%>
                </p>
                <p>
                  <%= f.label :password %><br />
                  <%= f.text_field :password, class: 'form-control' %>
                </p>
                <p>
                  <%= f.label :specialty %><br />
                  <%= f.text_field :specialty, class: 'form-control' %>
                </p>
                <p>
                  <%= f.label :location %><br />
                  <%= f.text_field :location, class: 'form-control' %>
                </p>
                <p>
                  <%= f.label :bio %><br />
                  <%= f.text_field :bio, class: 'form-control' %>
                </p>
              </div>
              <p><%= f.submit "Save Changes" %></p>
              <% end %>
          </p>
          <%= link_to 'Back', agent_profile_path(@agent) %>
        </center>
      </div>
    </div>
  </div>
</div>

app/views/agent_profile/index.html.erb
<nav class="navbar sticky-top navbar-light bg-light">
  <%= link_to "Real World", agent_profile_index_path %>
  <ul class="nav nav-pills" role="tablist">
    <%= link_to "Logout", agent_logout_path, :method => :delete %>
  </ul>
</nav>


<div class="sorting">
  <div class="btn-group btn-group-justified active" role="group" aria-label="...">
    <div class="btn-group" role="group">
      <button type="button" class="btn btn-default">Location</button>
    </div>
    <div class="btn-group" role="group">
      <button type="button" class="btn btn-default">Budget</button>
    </div>
    <div class="btn-group" role="group">
      <button type="button" class="btn btn-default">Size</button>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-12 agentprofileinfo">
        <center><h4>H O M E B U Y E R S</h4></center>
        <div class="scrollbar scrollbar-morpheus-den">
          <div class="force-overflow">
            <p>
              <% @users.each do |user| %>
                <ul>
                  <p class="listname">
                    <h4><%= user.name %> </h4>
                    Occupation: <%= user.occupation %>
                    Age: <%= user.age %>
                  </p>
                </ul>
              <% end %>
            </p>
          </div>
        </div>
    </div>
  </div>
</div>

app/views/agent_profile/show.html.erb
<nav class="navbar sticky-top navbar-light bg-light">
  <%= link_to "Real World", agent_profile_index_path %>
  <ul class="nav nav-pills" role="tablist">
    <%= link_to "Profile", agent_profile_path %>
    <%= link_to "Logout", agent_logout_path, :method => :delete %>
  </ul>
</nav>

<div class="messagenotification">
  <center>
    <% if @clientmessage.length === 0 %>
      <div> Sorry ! There is no message for you at the moment . </div>
    <% else %>
      <div>Congratulations! You have <span class="badge"><%= @clientmessage.length %></span> new message!</div>
    <% end %>
  </center>
</div>

<%= react_component("AgentProfile", props: @agent_profile_props, prerender: false) %>


<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="agentprofileinfo">
        <center>
          <p>
            <h5> <%= @agent.name %> </h5>
            <% if @clientreview.length === 0 %>
              <div> No rating right now . </div>
            <% else %>
              Average Rating: <% @clientreview.each do |review| %>
                <%= review.rating%>
              <% end %><br>
            <% end %>

            <p>
              Currently working with:
                <% resp = Response.where(agent: @agent).first %>
                <% if resp && resp.accept != nil %>
                    <%= resp.user.name %>
                <% else %>
                  0 client . 
                <% end %>
            </p>
            <span><img class="agentdisplay"src= '<%= @agent.img %>' alt="pic"></img> </span>
          </p>
          <p>
            <h5 class="title"> About Me </h5>
            <div class="scrollbar scrollbar-morpheus-den messagedagent">
              <b>email:</b> <%= @agent.email %> <br>
              <b>password:</b> ----- <%= @agent.password %> <br>
              <b>specialty:</b> <%= @agent.specialty %><br>
              <b>location:</b> <%= @agent.location %><br>
              <b>bio:</b> <%= @agent.bio %><br>
            </div>
          </p>
          <%= link_to 'Edit', edit_agent_profile_path(@agent) %>
        </center>
      </div>
    </div>


    <div class="col-md-6">
      <div class="agenthistory">
        <div class="messagedagent">
          <p><center><h5>Clients Messages</h5></center></p>
          <div class="scrollbar scrollbar-morpheus-den clientresponse">
            <div class="force-overflow">
              <% @clientmessage.each do |message| %>
                <ul>
                  <p>
                    <b><%= message.user.name %></b>
                      <span>
                        <%= link_to 'Respond', new_client_response_path(message.user), method: :get, :style => 'color: #FFFFFF;', class: "btn btn-success" %>
                        <%= link_to 'Delete', message, method: :delete, :style => 'color: #FFFFFF;', class: "btn btn-danger"%>
                      </span>
                  </p>
                  <p><%= message.content %></p>
                </ul>
              <% end %>
            </div>
          </div>
        </div>
        <div class="reviewedagent">
          <p><center><h5>Clients Reviews</h5></center></p>
          <div class="scrollbar scrollbar-morpheus-den messagedagent">
            <div class="force-overflow">
              <% @clientreview.each do |review| %>
                <ul>
                  <p><h5><%= review.user.name %></h5>
                  <p>
                    <b>Rating: </b><%= review.rating %><br>
                    <%= review.comment %>
                  </p>
                </ul>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>


  </div>
</div>