config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'hello_world#index', as: 'root'

    resources :response, controller: :response
    post '/response/:user_id', to: 'response#create', as: 'client_response'
    get '/response/:user_id/new', to: 'response#new', as: 'new_client_response'

    resources :message, controller: :message
    post '/message/:agent_id', to: 'message#create', as: 'agent_message'

    get '/agent_login', to: 'agent_session#new'
    post '/agent_login', to: 'agent_session#create'
    delete '/agent_logout', to: 'agent_session#destroy'
    get '/agent_register', to:'agent_register#new'
    post '/agent_register', to:'agent_register#create'
      resources :agent_profile, controller: :agent_profile

    get '/user_login', to: 'user_session#new'
    post '/user_login', to: 'user_session#create'
    delete '/user_logout', to: 'user_session#destroy'
    get '/user_register', to:'user_register#new'
    post '/user_register', to:'user_register#create'
      resources :user_profile, controller: :user_profile
      resources :agent, controller: :agent


end

app/controllers/user_profile_controller.rb
class UserProfileController < ApplicationController
  layout "user_profile"

  def index
    @client_profile_props = {
      name: "Michael Yuen"
    }
  end

  def show
    @user = User.find(params[:id])
    @agentmessage = Message.where(user_id: params[:id])
    @agentreview = Review.where(user_id: params[:id])

    @responses = Response.where(user_id: params[:id])
  end

  def new
        @register = Register.new
  end

  def create

  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to client_profile_path, :notice => "Your profile has been updated"
    else
      render "show"
    end
  end

  private
    def register_params
      params.permit(:name, :email, :password)
    end

    def user_params
      params.require(:user).permit(:name, :email, :password,:location, :budget, :size, :age, :address, :occupation)
    end
end

app/views/user_profile/edit.html.erb
<nav class="navbar sticky-top navbar-light bg-light">
  <a class="navbar-brand" href="http://localhost:3000/agent">Real World</a>
  <ul class="nav nav-pills" role="tablist">
    <li role="presentation"><a class="bannerbtn" href="http://localhost:3000/client_profile/1">Profile</a></li>
    <li role="presentation" class="active"><a class="bannerbtn" href="http://localhost:3000">Log out</a></li>
  </ul>
</nav>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="profileinfoedit">
        <center>
          <p>
              <h2> Edit Profile </h2>
              <h4><%= @user.name %></h4>
              <hr>
              <%= simple_form_for @user, url: user_profile_path(@user) do |f| %>
              <div class="scrollbar scrollbar-morpheus-den usereditpage">
                <p>
                  <%= f.label :email %><br />
                  <%= f.text_field :email %>
                </p>
                <p>
                  <%= f.label :password %><br />
                  <%= f.text_field :password %>
                </p>
                <p>
                  <%= f.label :location %><br />
                  <%= f.text_field :location %>
                </p>
                <p>
                  <%= f.label :budget %><br />
                  <%= f.text_field :budget %>
                </p>
                <p>
                  <%= f.label :size %><br />
                  <%= f.text_field :size %>
                </p>
                <p>
                  <%= f.label :age %><br />
                  <%= f.text_field :age %>
                </p>
                <p>
                  <%= f.label :address %><br />
                  <%= f.text_field :address %>
                </p>
                <p>
                  <%= f.label :occupation %><br />
                  <%= f.text_field :occupation %>
                </p>
              </div>
              <p><%= f.submit "Save Changes" %></p>
              <% end %>
          </p>
          <%= link_to 'Back', user_profile_path(@user) %>
        </center>
      </div>
    </div>
  </div>
</div>

app/views/user_profile/index.html.erb
<%= react_component("ClientProfile", props: @client_profile_props, prerender: false) %>

app/views/user_profile/show.html.erb
<nav class="navbar sticky-top navbar-light bg-light">
  <%= link_to "Real World", agent_index_path %>
  <ul class="nav nav-pills" role="tablist">
    <li role="presentation"><a class="bannerbtn" href="http://localhost:3000/user_profile/1">Profile</a></li>
    <%= link_to "Logout", user_logout_path, :method => :delete %>
  </ul>
</nav>

<div class="messagenotification">
  <center>
    <% if @responses.length === 0 %>
      <div> Sorry ! There is no message for you at the moment . </div>
    <% elsif @responses.length === 1 %>
      <div>Congratulations! You have <span class="badge"><%= @responses.length %></span> responded request!</div>
    <% else %>
        <div>Congratulations! You have <span class="badge"><%= @responses.length %></span> responded requests!</div>
    <% end %>
  </center>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="userinfo">
        <center><h2><%= @user.name %></h2>
        <p>
          <h5 class="title"> About Me </h5>
          <b>Occupation:</b> <%= @user.occupation %><br>
          <b>Age:</b> <%= @user.age %><br>
          <b>Address:</b> <%= @user.address %><br>
        </p>

        <p>
          <h5 class="title">Property Requirement</h5>
          <b>Area:</b> <%= @user.location %><br>
          <b>Budget:</b> <%= @user.budget %>,000<br>
          <b>Size:</b> <%= @user.size %><br>
        </p>
        <%= link_to 'Edit', edit_user_profile_path(@user) %>
        </center>
      </div>
    </div>

    <div class="col-md-6">
      <div class="history">
        <div class="acceptedrequest">
          <p><center><h5>Accepted Request</h5></center></p>
          <div class="scrollbar scrollbar-morpheus-den messagedagent">
            <div class="force-overflow">
              <% @responses.each do |response| %>
                <ul>
                  <p><b><%= response.agent.name %></b>
                    <span>
                      <%= link_to 'Accept', response, method: :put, :style => 'color: #FFFFFF;', class: "btn btn-success"%>
                      <%= link_to 'Reject', response, method: :delete, :style => 'color: #FFFFFF;', class: "btn btn-danger"%>
                    </span>
                  <p><%= response.content %></p>
                </ul>
              <% end %>
            </div>
          </div>
        </div>
        <div class="messagedagent">
          <p><center><h5>Unresponded Request</h5></center></p>
          <div class="scrollbar scrollbar-morpheus-den messagedagent">
            <div class="force-overflow">
              <% @agentmessage.each do |message| %>
                <ul>
                  <p><b><%= message.agent.name %></b></p>
                  <p><%= message.content %></p>
                </ul>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>